### PR TITLE
add sorting and ordering functionality to UI in the form of a sidebar

### PR DESCRIPTION
**Pull request by JakeMaciver**

### CODE REVIEW

**Comment by JakeMaciver** [comment]
i realise i have not completed this task via API calls using queries. I have done it using a utility function to sort them so we don't have to make a new API call every time we want to filter an item. The Trello board task says consider does this mean we have to call the API or is this okay?

**Comment by JakeMaciver** [comment]
also just realised my useEffect function actually calls on the API every time the sortItems change so it will be doing a request every time regardless

**Review by HeatherEver — COMMENTED** [review]
you're right, please change so that the API is doing the sorting rather than filtering on frontend side :)

**Review by robert112233 — APPROVED** [review]
Great work Jake, well done for expanding the original get reviews function instead of creating a new one. Merge 👍

**Pull request merged**
